In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("Output.csv")

In [3]:
data.head()

,Brand,Model,Year,Mileage_kmpl,Engine_CC,Horsepower,Fuel_Type,Transmission,Owner_Type,City,Kms_Driven,Insurance_Valid,Service_History,Accidents,Tax_Paid,Number_of_Doors,Seats,Registration_Age,Price
0,Toyota,Camry,2001,19.615852,1396.560379,120.571877,Hybrid,Automatic,First,Chennai,500928,1,1,0,1,4,5,24,353189
1,Hyundai,i20,2012,19.478608,1130.771005,137.021719,Petrol,Manual,First,Mumbai,211510,0,1,0,1,4,5,13,959694
2,Mahindra,Bolero,2008,17.469920,1766.466250,142.902960,Petrol,Automatic,First,Kolkata,333999,1,0,0,1,5,5,17,292022
3,BMW,X1,2015,21.295421,1506.627079,49.782079,Petrol,Manual,First,Pune,225930,1,1,3,1,4,5,10,2949453
4,Honda,Civic,2022,18.326833,1239.334935,121.505993,Diesel,Manual,Second,Kolkata,43404,1,0,0,1,5,5,3,636520

In [4]:
data.shape

(995244, 19)

In [5]:
data = data.drop('Registration_Age', axis = 1)

In [6]:
data.shape

(995244, 18)

In [7]:
data['Car_Age'] = 2026 - data['Year']

In [8]:
data.head()

,Brand,Model,Year,Mileage_kmpl,Engine_CC,Horsepower,Fuel_Type,Transmission,Owner_Type,City,Kms_Driven,Insurance_Valid,Service_History,Accidents,Tax_Paid,Number_of_Doors,Seats,Price,Car_Age
0,Toyota,Camry,2001,19.615852,1396.560379,120.571877,Hybrid,Automatic,First,Chennai,500928,1,1,0,1,4,5,353189,25
1,Hyundai,i20,2012,19.478608,1130.771005,137.021719,Petrol,Manual,First,Mumbai,211510,0,1,0,1,4,5,959694,14
2,Mahindra,Bolero,2008,17.469920,1766.466250,142.902960,Petrol,Automatic,First,Kolkata,333999,1,0,0,1,5,5,292022,18
3,BMW,X1,2015,21.295421,1506.627079,49.782079,Petrol,Manual,First,Pune,225930,1,1,3,1,4,5,2949453,11
4,Honda,Civic,2022,18.326833,1239.334935,121.505993,Diesel,Manual,Second,Kolkata,43404,1,0,0,1,5,5,636520,4

In [9]:
data['Transmission'] = data['Transmission'].map({'Automatic': 0, 'Manual': 1})

In [10]:
data.head()

,Brand,Model,Year,Mileage_kmpl,Engine_CC,Horsepower,Fuel_Type,Transmission,Owner_Type,City,Kms_Driven,Insurance_Valid,Service_History,Accidents,Tax_Paid,Number_of_Doors,Seats,Price,Car_Age
0,Toyota,Camry,2001,19.615852,1396.560379,120.571877,Hybrid,0,First,Chennai,500928,1,1,0,1,4,5,353189,25
1,Hyundai,i20,2012,19.478608,1130.771005,137.021719,Petrol,1,First,Mumbai,211510,0,1,0,1,4,5,959694,14
2,Mahindra,Bolero,2008,17.469920,1766.466250,142.902960,Petrol,0,First,Kolkata,333999,1,0,0,1,5,5,292022,18
3,BMW,X1,2015,21.295421,1506.627079,49.782079,Petrol,1,First,Pune,225930,1,1,3,1,4,5,2949453,11
4,Honda,Civic,2022,18.326833,1239.334935,121.505993,Diesel,1,Second,Kolkata,43404,1,0,0,1,5,5,636520,4

In [11]:
data = data.drop(columns=['Horsepower','City','Service_History','Accidents','Tax_Paid','Number_of_Doors'], axis = 1)

In [12]:
data.shape

(995244, 13)

In [13]:
data.head()

,Brand,Model,Year,Mileage_kmpl,Engine_CC,Fuel_Type,Transmission,Owner_Type,Kms_Driven,Insurance_Valid,Seats,Price,Car_Age
0,Toyota,Camry,2001,19.615852,1396.560379,Hybrid,0,First,500928,1,5,353189,25
1,Hyundai,i20,2012,19.478608,1130.771005,Petrol,1,First,211510,0,5,959694,14
2,Mahindra,Bolero,2008,17.469920,1766.466250,Petrol,0,First,333999,1,5,292022,18
3,BMW,X1,2015,21.295421,1506.627079,Petrol,1,First,225930,1,5,2949453,11
4,Honda,Civic,2022,18.326833,1239.334935,Diesel,1,Second,43404,1,5,636520,4

In [14]:
data = pd.get_dummies(data, columns = ['Brand','Model','Fuel_Type'], dtype = int)

In [15]:
data.head()

,Year,Mileage_kmpl,Engine_CC,Transmission,Owner_Type,Kms_Driven,Insurance_Valid,Seats,Price,Car_Age,...,Model_X1,Model_X3,Model_XUV700,Model_Yaris,Model_i20,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Hybrid,Fuel_Type_Petrol
0,2001,19.615852,1396.560379,0,First,500928,1,5,353189,25,...,0,0,0,0,0,0,0,0,1,0
1,2012,19.478608,1130.771005,1,First,211510,0,5,959694,14,...,0,0,0,0,1,0,0,0,0,1
2,2008,17.469920,1766.466250,0,First,333999,1,5,292022,18,...,0,0,0,0,0,0,0,0,0,1
3,2015,21.295421,1506.627079,1,First,225930,1,5,2949453,11,...,1,0,0,0,0,0,0,0,0,1
4,2022,18.326833,1239.334935,1,Second,43404,1,5,636520,4,...,0,0,0,0,0,0,1,0,0,0

In [16]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data['Owner_Type'] = le.fit_transform(data['Owner_Type'])

In [17]:
data.head()

,Year,Mileage_kmpl,Engine_CC,Transmission,Owner_Type,Kms_Driven,Insurance_Valid,Seats,Price,Car_Age,...,Model_X1,Model_X3,Model_XUV700,Model_Yaris,Model_i20,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Hybrid,Fuel_Type_Petrol
0,2001,19.615852,1396.560379,0,0,500928,1,5,353189,25,...,0,0,0,0,0,0,0,0,1,0
1,2012,19.478608,1130.771005,1,0,211510,0,5,959694,14,...,0,0,0,0,1,0,0,0,0,1
2,2008,17.469920,1766.466250,0,0,333999,1,5,292022,18,...,0,0,0,0,0,0,0,0,0,1
3,2015,21.295421,1506.627079,1,0,225930,1,5,2949453,11,...,1,0,0,0,0,0,0,0,0,1
4,2022,18.326833,1239.334935,1,2,43404,1,5,636520,4,...,0,0,0,0,0,0,1,0,0,0

In [18]:
data.shape

(995244, 67)

In [19]:
data.columns

Index(['Year', 'Mileage_kmpl', 'Engine_CC', 'Transmission', 'Owner_Type',
       'Kms_Driven', 'Insurance_Valid', 'Seats', 'Price', 'Car_Age',
       'Brand_Audi', 'Brand_BMW', 'Brand_Ford', 'Brand_Honda', 'Brand_Hyundai',
       'Brand_Kia', 'Brand_Mahindra', 'Brand_Mercedes', 'Brand_Nissan',
       'Brand_Skoda', 'Brand_Tata', 'Brand_Toyota', 'Brand_Volkswagen',
       'Model_3 Series', 'Model_A4', 'Model_Amaze', 'Model_Bolero',
       'Model_C-Class', 'Model_Camry', 'Model_Carens', 'Model_City',
       'Model_Civic', 'Model_Corolla', 'Model_Creta', 'Model_E-Class',
       'Model_EcoSport', 'Model_Endeavour', 'Model_Figo', 'Model_GLA',
       'Model_Harrier', 'Model_Kicks', 'Model_Kushaq', 'Model_Magnite',
       'Model_Nexon', 'Model_Octavia', 'Model_Polo', 'Model_Punch', 'Model_Q3',
       'Model_Q5', 'Model_Scorpio', 'Model_Seltos', 'Model_Slavia',
       'Model_Sonet', 'Model_Sunny', 'Model_Taigun', 'Model_Verna',
       'Model_Virtus', 'Model_X1', 'Model_X3', 'Model_XUV700', 'Model_Yaris',
       'Model_i20', 'Fuel_Type_CNG', 'Fuel_Type_Diesel', 'Fuel_Type_Electric',
       'Fuel_Type_Hybrid', 'Fuel_Type_Petrol'],
      dtype='object')

In [20]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler_feature = ['Year', 'Mileage_kmpl', 'Engine_CC','Owner_Type', 'Kms_Driven','Car_Age']

data[scaler_feature] = scaler.fit_transform(data[scaler_feature])

In [21]:
data.head()

,Year,Mileage_kmpl,Engine_CC,Transmission,Owner_Type,Kms_Driven,Insurance_Valid,Seats,Price,Car_Age,...,Model_X1,Model_X3,Model_XUV700,Model_Yaris,Model_i20,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Hybrid,Fuel_Type_Petrol
0,-1.522928,0.422888,-0.297078,0,-0.768107,1.807415,1,5,353189,1.522928,...,0,0,0,0,0,0,0,0,1,0
1,0.002603,0.387056,-1.014839,1,-0.768107,0.066750,0,5,959694,-0.002603,...,0,0,0,0,1,0,0,0,0,1
2,-0.552136,-0.137367,0.701849,0,-0.768107,0.803443,1,5,292022,0.552136,...,0,0,0,0,0,0,0,0,0,1
3,0.418657,0.861386,0.000156,1,-0.768107,0.153477,1,5,2949453,-0.418657,...,1,0,0,0,0,0,0,0,0,1
4,1.389449,0.086354,-0.721663,1,1.036480,-0.944300,1,5,636520,-1.389449,...,0,0,0,0,0,0,1,0,0,0

In [22]:
X = data.drop('Price', axis = 1)

In [23]:
X.shape

(995244, 66)

In [24]:
y = data['Price']

In [25]:
y.shape

(995244,)

In [26]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.20, random_state = 42)

In [27]:
X_train.shape

(796195, 66)

In [28]:
X_test.shape

(199049, 66)

In [29]:
from sklearn.model_selection import cross_val_score
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV

In [30]:
xgb = XGBRegressor()

In [31]:
scores = cross_val_score(
    xgb,
    X,
    y,
    cv=5,
    scoring='r2'
)

In [32]:
print("CV Scores:", scores)
print("Average CV R2:", scores.mean())

CV Scores: [0.73517513 0.73549992 0.7337563  0.73617852 0.73388273]
Average CV R2: 0.7348985195159912

In [33]:
from sklearn.model_selection import RandomizedSearchCV

params = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7, 9],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'subsample': [0.8, 1.0]
}

random = RandomizedSearchCV(
    estimator= xgb,
    param_distributions=params,
    n_iter = 10,
    cv = 5,
    scoring = 'r2',
    random_state = 42

)

In [34]:
random.fit(X_train, y_train)

RandomizedSearchCV(cv=5,
                   estimator=XGBRegressor(base_score=None, booster=None,
                                          callbacks=None,
                                          colsample_bylevel=None,
                                          colsample_bynode=None,
                                          colsample_bytree=None, device=None,
                                          early_stopping_rounds=None,
                                          enable_categorical=False,
                                          eval_metric=None, feature_types=None,
                                          feature_weights=None, gamma=None,
                                          grow_policy=None,
                                          importance_type=None,
                                          interaction_constraint...
                                          max_cat_to_onehot=None,
                                          max_delta_step=None, max_depth=None,
                                          max_leaves=None,
                                          min_child_weight=None, missing=nan,
                                          monotone_constraints=None,
                                          multi_strategy=None,
                                          n_estimators=None, n_jobs=None,
                                          num_parallel_tree=None, ...),
                   param_distributions={'learning_rate': [0.01, 0.05, 0.1, 0.2],
                                        'max_depth': [3, 5, 7, 9],
                                        'n_estimators': [100, 200, 300],
                                        'subsample': [0.8, 1.0]},
                   random_state=42, scoring='r2')

In [35]:
print(random.best_params_)

{'subsample': 1.0, 'n_estimators': 300, 'max_depth': 3, 'learning_rate': 0.2}

In [36]:
print(random.best_score_)

0.736442482471466

In [37]:
best_model = random.best_estimator_
print(best_model)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.2, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

In [38]:
y_pred = random.predict(X_test)

In [39]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [40]:
r2_random = r2_score(y_test, y_pred)
mae_random = mean_absolute_error(y_test, y_pred)
mse_random = mean_squared_error(y_test, y_pred)

In [41]:
print("R2 Score: ", r2_random)
print("MSE: ", mse_random)
print("MAE: ", mae_random)

R2 Score:  0.7340669631958008
MSE:  197383880704.0
MAE:  330692.6875

In [42]:
import pickle

# Save model
with open('model.pkl', 'wb') as file:
    pickle.dump(random, file)

In [44]:
import pickle

# Save scaler
pickle.dump(scaler, open("scaler.pkl", "wb"))

print("Scaler Saved Successfully")

Scaler Saved Successfully

In [45]:
print(X.columns.tolist())

['Year', 'Mileage_kmpl', 'Engine_CC', 'Transmission', 'Owner_Type', 'Kms_Driven', 'Insurance_Valid', 'Seats', 'Car_Age', 'Brand_Audi', 'Brand_BMW', 'Brand_Ford', 'Brand_Honda', 'Brand_Hyundai', 'Brand_Kia', 'Brand_Mahindra', 'Brand_Mercedes', 'Brand_Nissan', 'Brand_Skoda', 'Brand_Tata', 'Brand_Toyota', 'Brand_Volkswagen', 'Model_3 Series', 'Model_A4', 'Model_Amaze', 'Model_Bolero', 'Model_C-Class', 'Model_Camry', 'Model_Carens', 'Model_City', 'Model_Civic', 'Model_Corolla', 'Model_Creta', 'Model_E-Class', 'Model_EcoSport', 'Model_Endeavour', 'Model_Figo', 'Model_GLA', 'Model_Harrier', 'Model_Kicks', 'Model_Kushaq', 'Model_Magnite', 'Model_Nexon', 'Model_Octavia', 'Model_Polo', 'Model_Punch', 'Model_Q3', 'Model_Q5', 'Model_Scorpio', 'Model_Seltos', 'Model_Slavia', 'Model_Sonet', 'Model_Sunny', 'Model_Taigun', 'Model_Verna', 'Model_Virtus', 'Model_X1', 'Model_X3', 'Model_XUV700', 'Model_Yaris', 'Model_i20', 'Fuel_Type_CNG', 'Fuel_Type_Diesel', 'Fuel_Type_Electric', 'Fuel_Type_Hybrid', 'Fuel_Type_Petrol']